# Generated by Django 6.0.2 on 2026-02-24 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='snippets_ta_title_40c058_idx')],
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('note', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='snippets', to='snippets.tag')),
            ],
            options={
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['title'], name='snippets_sn_title_2486e2_idx')],
            },
        ),
    ]
